version: '2'
services:
    db:
        image: mysql
        container_name: jsonapi-mysql
        volumes:
            - "./data/db:/var/lib/mysql"
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: api
            MYSQL_USER: root
    php:
        container_name: jsonapi-php
        build:
            context: php7-fpm
            args:
                TIMEZONE: Europe/Berlin
        volumes:
            - ./app:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
            - ./php7-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
    nginx:
        container_name: jsonapi-nginx
        build: nginx
        ports:
            - 88:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx